name: Run Snyk scan on PRs

on:
  pull_request:
    branches:
      - master**

jobs:
  scan-for-new-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            8
            11

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: mqtt-cli

      - name: Check for new issues
        uses: hivemq/hivemq-snyk-composite-action@v2.0.0
        with:
          snyk-args: --configuration-matching=^runtimeClasspath$ mqtt-cli
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          snyk-baseline-project-id: ${{ secrets.SNYK_PROJECT_ID_MASTER }}
