name: Run Snyk monitor on push

on:
  push:
    branches:
      - master**

jobs:
  run-snyk-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            11

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: mqtt-cli

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk monitor
        shell: bash
        run: snyk monitor --configuration-matching=^runtimeClasspath$ --target-reference=${{ github.ref_name }} mqtt-cli
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
